name: manage-azure-policy-dc6f39ab
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Private_endpoint_should_be_enabled_for_MySQL_servers_7595c971-233d-4bcf-bd18-596129188c49/**'
#      - .github/workflows/manage-azure-policy-dc6f39ab.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_dc6f39ab}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Private_endpoint_should_be_enabled_for_MySQL_servers_7595c971-233d-4bcf-bd18-596129188c49/**
