name: manage-azure-policy-886cc77b
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Synapse_workspaces_should_use_private_link_72d11df1-dd8a-41f7-8925-b05b960ebafc/**'
#      - .github/workflows/manage-azure-policy-886cc77b.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_886cc77b}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Synapse_workspaces_should_use_private_link_72d11df1-dd8a-41f7-8925-b05b960ebafc/**
