name: manage-azure-policy-ec08e09a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Event_Grid_topics_should_use_private_link_4b90e17e-8448-49db-875e-bd83fb6f804f/**'
#      - .github/workflows/manage-azure-policy-ec08e09a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ec08e09a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Event_Grid_topics_should_use_private_link_4b90e17e-8448-49db-875e-bd83fb6f804f/**
