name: manage-azure-policy-be45865c
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Public_network_access_on_Azure_IoT_Hub_should_be_disabled_2d6830fb-07eb-48e7-8c4d-2a442b35f0fb/**'
#      - .github/workflows/manage-azure-policy-be45865c.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_be45865c}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Public_network_access_on_Azure_IoT_Hub_should_be_disabled_2d6830fb-07eb-48e7-8c4d-2a442b35f0fb/**
