name: manage-azure-policy-0ef9f5b1
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_SignalR_Service_should_use_a_Private_Link_enabled_SKU_464a1620-21b5-448d-8ce6-d4ac6d1bc49a/**'
#      - .github/workflows/manage-azure-policy-0ef9f5b1.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_0ef9f5b1}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_SignalR_Service_should_use_a_Private_Link_enabled_SKU_464a1620-21b5-448d-8ce6-d4ac6d1bc49a/**
