name: manage-azure-policy-d7948a80
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Managed_disks_should_disable_public_network_access_8405fdab-1faf-48aa-b702-999c9c172094/**'
#      - .github/workflows/manage-azure-policy-d7948a80.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d7948a80}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Managed_disks_should_disable_public_network_access_8405fdab-1faf-48aa-b702-999c9c172094/**
