name: manage-azure-policy-2043fd92
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/_Preview_Azure_Key_Vault_should_disable_public_network_access_55615ac9-af46-4a59-874e-391cc3dfb490/**'
#      - .github/workflows/manage-azure-policy-2043fd92.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_2043fd92}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/_Preview_Azure_Key_Vault_should_disable_public_network_access_55615ac9-af46-4a59-874e-391cc3dfb490/**
