name: manage-azure-policy-3df9a21d
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/MariaDB_server_should_use_a_virtual_network_service_endpoint_dfbd9a64-6114-48de-a47d-90574dc2e489/**'
#      - .github/workflows/manage-azure-policy-3df9a21d.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_3df9a21d}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/MariaDB_server_should_use_a_virtual_network_service_endpoint_dfbd9a64-6114-48de-a47d-90574dc2e489/**
