name: manage-azure-policy-709e501d
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_API_for_FHIR_should_use_private_link_1ee56206-5dd1-42ab-b02d-8aae8b1634ce/**'
#      - .github/workflows/manage-azure-policy-709e501d.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_709e501d}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_API_for_FHIR_should_use_private_link_1ee56206-5dd1-42ab-b02d-8aae8b1634ce/**
