name: manage-azure-policy-6d5e7334
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Public_network_access_should_be_disabled_for_MySQL_flexible_servers_c9299215-ae47-4f50-9c54-8a392f68a052/**'
#      - .github/workflows/manage-azure-policy-6d5e7334.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_6d5e7334}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Public_network_access_should_be_disabled_for_MySQL_flexible_servers_c9299215-ae47-4f50-9c54-8a392f68a052/**
