name: manage-azure-policy-c8a73bce
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/CosmosDB_accounts_should_use_private_link_58440f8a-10c5-4151-bdce-dfbaad4a20b7/**'
#      - .github/workflows/manage-azure-policy-c8a73bce.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_c8a73bce}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/CosmosDB_accounts_should_use_private_link_58440f8a-10c5-4151-bdce-dfbaad4a20b7/**
