name: manage-azure-policy-782e1acf
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Cognitive_Search_service_should_use_a_SKU_that_supports_private_link_a049bf77-880b-470f-ba6d-9f21c530cf83/**'
#      - .github/workflows/manage-azure-policy-782e1acf.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_782e1acf}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Cognitive_Search_service_should_use_a_SKU_that_supports_private_link_a049bf77-880b-470f-ba6d-9f21c530cf83/**
