name: manage-azure-policy-ec4dd97a
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Append_a_tag_and_its_value_to_resource_groups_49c88fc8-6fd1-46fd-a676-f12d1d3a4c71/**'
#      - .github/workflows/manage-azure-policy-ec4dd97a.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ec4dd97a}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Append_a_tag_and_its_value_to_resource_groups_49c88fc8-6fd1-46fd-a676-f12d1d3a4c71/**
