name: manage-azure-policy-cd9e5d42
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Cosmos_DB_throughput_should_be_limited_0b7ef78e-a035-4f23-b9bd-aff122a1b1cf/**'
#      - .github/workflows/manage-azure-policy-cd9e5d42.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_cd9e5d42}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Cosmos_DB_throughput_should_be_limited_0b7ef78e-a035-4f23-b9bd-aff122a1b1cf/**
