name: manage-azure-policy-d4b183b1
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Inherit_a_tag_from_the_resource_group_if_missing_ea3f2387-9b95-492a-a190-fcdc54f7b070/**'
#      - .github/workflows/manage-azure-policy-d4b183b1.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d4b183b1}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Inherit_a_tag_from_the_resource_group_if_missing_ea3f2387-9b95-492a-a190-fcdc54f7b070/**
