name: manage-azure-policy-480d9831
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Cache_for_Redis_should_use_private_link_7803067c-7d34-46e3-8c79-0ca68fc4036d/**'
#      - .github/workflows/manage-azure-policy-480d9831.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_480d9831}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Cache_for_Redis_should_use_private_link_7803067c-7d34-46e3-8c79-0ca68fc4036d/**
