name: manage-azure-policy-e3bf2dfc
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Event_Grid_topics_should_disable_public_network_access_1adadefe-5f21-44f7-b931-a59b54ccdb45/**'
#      - .github/workflows/manage-azure-policy-e3bf2dfc.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_e3bf2dfc}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Event_Grid_topics_should_disable_public_network_access_1adadefe-5f21-44f7-b931-a59b54ccdb45/**
