name: manage-azure-policy-50188b5c
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Event_Grid_domains_should_use_private_link_9830b652-8523-49cc-b1b3-e17dce1127ca/**'
#      - .github/workflows/manage-azure-policy-50188b5c.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_50188b5c}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Event_Grid_domains_should_use_private_link_9830b652-8523-49cc-b1b3-e17dce1127ca/**
