name: manage-azure-policy-1797d1a4
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Log_Analytics_workspaces_should_block_log_ingestion_and_querying_from_public_networks_6c53d030-cc64-46f0-906d-2bc061cd1334/**'
#      - .github/workflows/manage-azure-policy-1797d1a4.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_1797d1a4}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Log_Analytics_workspaces_should_block_log_ingestion_and_querying_from_public_networks_6c53d030-cc64-46f0-906d-2bc061cd1334/**
