name: manage-azure-policy-ff6c0194
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Cognitive_Search_services_should_use_private_link_0fda3595-9f2b-4592-8675-4231d6fa82fe/**'
#      - .github/workflows/manage-azure-policy-ff6c0194.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_ff6c0194}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Cognitive_Search_services_should_use_private_link_0fda3595-9f2b-4592-8675-4231d6fa82fe/**
