name: manage-azure-policy-06ac1e45
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Service_Bus_namespaces_should_use_private_link_1c06e275-d63d-4540-b761-71f364c2111d/**'
#      - .github/workflows/manage-azure-policy-06ac1e45.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_06ac1e45}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Service_Bus_namespaces_should_use_private_link_1c06e275-d63d-4540-b761-71f364c2111d/**
